### ISSUE TITLE
Simplify the creation of a new client

### ISSUE THREAD

**Issue by kumarharsh** [playlyfe/playlyfe-node-sdk#7]
Right now, for switching to v2, it requires an "endpoint" property to be explicitly passed to the sdk. The onus of knowing the full endpoint should not fall upon the developer. Only knowing the API version should be enough.

Suggestion: Deprecate the `endpoint` option, replace with a `version` option

**Comment by pyros2097** [comment]
No you don't need to pass an endpoint .. you can just pass a version, it is by default v2 .. which version are you using? I'll remove the endpoint..

**Comment by kumarharsh** [comment]
Oh, I missed the version option at the start. Sorry. Closing the issue.
