### ISSUE TITLE
Errors from the platform don't pass the error to the callback

### ISSUE THREAD

**Issue by kumarharsh** [playlyfe/playlyfe-node-sdk#8]
Any error from the platform does not get passed to the error variable in the api callback, but rather to the _body_ variable. This makes it more painful for developers to write clean code, and again the onus falls on the developer to identify what is an error.

**Comment by pyros2097** [comment]
Fixed. Now there is a PlaylyfeException Object thrown on any Playlyfe error and a normal error is thrown on any other errors like network error.
